apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-user
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user
spec:
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
        - name: postgres-user
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: ttsuser
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgres-pvc-user
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-user
spec:
  selector:
    app: postgres-user
  ports:
    - port: 5432
      targetPort: 5432