apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-ticket
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-ticket
spec:
  selector:
    matchLabels:
      app: postgres-ticket
  template:
    metadata:
      labels:
        app: postgres-ticket
    spec:
      containers:
        - name: postgres-ticket
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: ttsticket
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgres-pvc-ticket
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-ticket
spec:
  selector:
    app: postgres-ticket
  ports:
    - port: 5433
      targetPort: 5432