apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-ticket
  template:
    metadata:
      labels:
        app: backend-ticket
    spec:
      containers:
        - name: app
          image: pikachust8811/tts-backend-ticket:v1
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: postgres-ticket
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend-ticket
spec:
  type: NodePort
  selector:
    app: backend-ticket
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      protocol: TCP